apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: firefly
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi