apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-upload
  namespace: firefly
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 2Gi