apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tritus255/homelab.git
    targetRevision: main
    path: apps/dab/base
  destination:
    server: https://kubernetes.default.svc
    namespace: dab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
